apiVersion: v1
kind: Namespace
metadata:
  name: struts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: struts
  namespace: struts
  labels:
    app: struts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: struts
  template:
    metadata:
      labels:
        app: struts
    spec:
      containers:
      - name: struts
        image: reyl/struts:0.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: struts
  namespace: struts
spec:
  type: NodePort
  selector:
    app: struts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.struts.struts
    namespace: struts
  spec:
    egress: []
    file: []
    ingress:
    - action: allow
      applications:
      - HTTP
      name: nv.struts.struts-ingress-0
      ports: any
      priority: 0
      selector:
        name: Workload:ingress
        original_name: ""
    process:
    - action: allow
      name: java
      path: /usr/local/openjdk-8/bin/java
    - action: allow
      name: pause
      path: /pause
    target:
      policymode: Protect
      selector:
        criteria:
        - key: service
          op: =
          value: struts.struts
        - key: domain
          op: =
          value: struts
        name: nv.struts.struts
        original_name: ""
kind: List
metadata: null
